package com.suprbeta.supabase

import kotlin.test.*
import kotlin.test.Test

/**
 * Unit tests for the schema-scoped MCP role SQL generated by
 * [SelfHostedSupabaseManagementService].
 *
 * True database isolation relies on these SQL statements being correct.
 * Regressions here would silently grant cross-schema access, so we test
 * each statement exhaustively.
 */
class SelfHostedSchemaIsolationTest {

    // ── Role creation statements ──────────────────────────────────────────

    @Test
    fun `roleCreationStatements returns exactly 9 statements`() {
        // CREATE ROLE + GRANT USAGE + GRANT CRUD TABLES + ALTER DEFAULT TABLES +
        // ALTER DEFAULT SEQUENCES + ALTER ROLE search_path + GRANT authenticator +
        // CREATE FUNCTION execute_scoped_sql + GRANT EXECUTE
        assertEquals(9, SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc").size)
    }

    @Test
    fun `roleCreationStatements first statement creates role with NOLOGIN`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertEquals("CREATE ROLE proj_abc_rpc NOLOGIN", stmts[0])
    }

    @Test
    fun `roleCreationStatements grants USAGE on the schema`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertTrue(stmts.any { it == "GRANT USAGE ON SCHEMA proj_abc TO proj_abc_rpc" },
            "Expected GRANT USAGE statement, got: $stmts")
    }

    @Test
    fun `roleCreationStatements grants CRUD on all current tables`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertTrue(stmts.any {
            it.contains("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA proj_abc TO proj_abc_rpc")
        }, "Expected GRANT SELECT,INSERT,UPDATE,DELETE statement, got: $stmts")
    }

    @Test
    fun `roleCreationStatements sets default privileges for future tables`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertTrue(stmts.any {
            it.contains("ALTER DEFAULT PRIVILEGES") &&
            it.contains("proj_abc") &&
            it.contains("SELECT, INSERT, UPDATE, DELETE ON TABLES TO proj_abc_rpc")
        }, "Expected ALTER DEFAULT PRIVILEGES for tables, got: $stmts")
    }

    @Test
    fun `roleCreationStatements grants sequence access for default privileges`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertTrue(stmts.any {
            it.contains("ALTER DEFAULT PRIVILEGES") &&
            it.contains("USAGE, SELECT ON SEQUENCES TO proj_abc_rpc")
        }, "Expected ALTER DEFAULT PRIVILEGES for sequences, got: $stmts")
    }

    @Test
    fun `roleCreationStatements pins search_path to own schema`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        assertTrue(stmts.any {
            it.contains("ALTER ROLE proj_abc_rpc SET search_path = proj_abc")
        }, "Expected ALTER ROLE SET search_path statement, got: $stmts")
    }

    @Test
    fun `roleCreationStatements uses schema name as prefix for role`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_deadbeef")
        // Every statement that mentions a role name must use proj_deadbeef_rpc
        val withRole = stmts.filter { it.contains("_rpc") }
        assertTrue(withRole.isNotEmpty())
        assertTrue(withRole.all { it.contains("proj_deadbeef_rpc") },
            "All role references must use proj_deadbeef_rpc, got: $withRole")
    }

    @Test
    fun `roleCreationStatements does not reference other schemas`() {
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_isolated")
        // No statement should reference public schema or any other schema name
        assertTrue(stmts.none { it.contains("public.") },
            "Role statements must not reference public schema, got: $stmts")
    }

    @Test
    fun `roleCreationStatements are identical for different schema names (structure check)`() {
        val a = SelfHostedSupabaseManagementService.roleCreationStatements("proj_aaa")
        val b = SelfHostedSupabaseManagementService.roleCreationStatements("proj_bbb")
        // Structure should be the same; only schema name differs
        assertEquals(a.size, b.size)
        a.zip(b).forEach { (sa, sb) ->
            assertEquals(
                sa.replace("proj_aaa", "<SCHEMA>"),
                sb.replace("proj_bbb", "<SCHEMA>"),
                "Statement structure must be identical across schemas"
            )
        }
    }

    // ── Role drop statement ───────────────────────────────────────────────

    @Test
    fun `roleDropStatement uses IF EXISTS for safety`() {
        val stmt = SelfHostedSupabaseManagementService.roleDropStatement("proj_abc")
        assertTrue(stmt.contains("IF EXISTS"), "DROP ROLE must use IF EXISTS")
    }

    @Test
    fun `roleDropStatement drops the correct role`() {
        val stmt = SelfHostedSupabaseManagementService.roleDropStatement("proj_abc12345")
        assertEquals("DROP ROLE IF EXISTS proj_abc12345_rpc", stmt)
    }

    @Test
    fun `roleDropStatement does not drop the schema itself`() {
        val stmt = SelfHostedSupabaseManagementService.roleDropStatement("proj_abc")
        assertFalse(stmt.contains("SCHEMA"), "Role drop statement must not touch the schema")
    }

    // ── Interaction with adaptSqlForSchema ────────────────────────────────

    @Test
    fun `role grant statements are not affected by adaptSqlForSchema`() {
        // Role grants do NOT use public. prefix, so adaptSqlForSchema should leave them unchanged
        val stmts = SelfHostedSupabaseManagementService.roleCreationStatements("proj_abc")
        stmts.forEach { stmt ->
            val adapted = SelfHostedSupabaseManagementService.adaptSqlForSchema(stmt, "proj_abc")
            assertEquals(stmt, adapted,
                "adaptSqlForSchema must not alter role grant statements: $stmt")
        }
    }

    @Test
    fun `role drop statement is not affected by adaptSqlForSchema`() {
        val stmt = SelfHostedSupabaseManagementService.roleDropStatement("proj_abc")
        val adapted = SelfHostedSupabaseManagementService.adaptSqlForSchema(stmt, "proj_abc")
        assertEquals(stmt, adapted, "adaptSqlForSchema must not alter role drop statement")
    }

    @Test
    fun `buildUpdateConfiguredSchemasCommand recreates rest with reconciled schema list`() {
        val command = SelfHostedSupabaseManagementService.buildUpdateConfiguredSchemasCommand(
            "/opt/supabase/docker",
            listOf("public", "storage", "graphql_public", "proj_abc")
        )

        assertTrue(command.contains("cd /opt/supabase/docker"))
        assertTrue(command.contains("PGRST_DB_SCHEMAS=public,storage,graphql_public,proj_abc"))
        assertTrue(command.contains("docker compose up -d --force-recreate rest"))
    }
}
